Traceback (most recent call last):
  File "/home/goodwill/miniconda3/envs/pycourse_test/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/goodwill/miniconda3/envs/pycourse_test/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goodwill/miniconda3/envs/pycourse_test/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goodwill/miniconda3/envs/pycourse_test/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/goodwill/miniconda3/envs/pycourse_test/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/goodwill/miniconda3/envs/pycourse_test/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/goodwill/miniconda3/envs/pycourse_test/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numba import njit

@njit
def compute_pi_mc_numba(n=1000):
    x = np.random.rand(n,2)*2 - 1
    ct = 0
    for i in range(n):
        ct += x[i,0]**2 + x[i,1]**2 < 1
    return 4 * ct / n
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[28], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumba[39;00m [38;5;28;01mimport[39;00m njit
[1;32m      3[0m [38;5;129m@njit[39m
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mcompute_pi_mc_numba[39m(n[38;5;241m=[39m[38;5;241m1000[39m):
[1;32m      5[0m     x [38;5;241m=[39m np[38;5;241m.[39mrandom[38;5;241m.[39mrand(n,[38;5;241m2[39m)[38;5;241m*[39m[38;5;241m2[39m [38;5;241m-[39m [38;5;241m1[39m

[0;31mModuleNotFoundError[0m: No module named 'numba'

